## Travis CI Integration

language: objective-c

env:
 global:
  - EnableNuGetPackageRestore=true 
 matrix:
  - MONO_VER="3.1.12"

before_install:
 - wget "http://download.mono-project.com/archive/${MONO_VER}/macos-10-x86/MonoFramework-MDK-${MONO_VER}.macos10.xamarin.x86.pkg"
 - sudo installer -pkg "MonoFramework-MDK-${MONO_VER}.macos10.xamarin.x86.pkg" -target /

script:
  - cd src/
  - xbuild SpruceJS.sln
  - mono ../lib/xunit-1.9.1/xunit.console.clr4.x86.exe Tests/SpruceJS.Test/bin/debug/SpruceJS.Test.dll